/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'isCorrect' : boolean, 'answerText' : string }
export interface AnswerDTO { 'answerText' : string }
export interface IQTestScoreReport {
  'finalIQScore' : bigint,
  'attempts' : Array<SessionAttempt>,
  'normalizedIQScore' : number,
  'correctAnswers' : bigint,
  'elapsedTime' : bigint,
  'averageDifficulty' : number,
  'resultSummary' : string,
}
export interface QuestionDTO {
  'id' : string,
  'answers' : Array<AnswerDTO>,
  'difficulty' : number,
  'explanation' : string,
  'questionText' : string,
}
export interface SessionAttempt {
  'difficulty' : number,
  'chosenAnswerIndex' : bigint,
  'isCorrect' : boolean,
  'questionId' : string,
  'responseTime' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<[number, string, Array<Answer>, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateIQScore' : ActorMethod<
    [Array<SessionAttempt>, bigint],
    IQTestScoreReport
  >,
  'deleteQuestion' : ActorMethod<[string], undefined>,
  'getCachedScore' : ActorMethod<[Principal], [] | [IQTestScoreReport]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuestionCount' : ActorMethod<[], bigint>,
  'getQuestionsInRange' : ActorMethod<[number, number], Array<QuestionDTO>>,
  'getRecommendedQuestions' : ActorMethod<
    [number, number, bigint],
    Array<QuestionDTO>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchByText' : ActorMethod<[string], Array<QuestionDTO>>,
  'submitAnswer' : ActorMethod<[string, bigint, bigint], boolean>,
  'updateQuestion' : ActorMethod<
    [string, number, string, Array<Answer>, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];