/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Answer = IDL.Record({
  'isCorrect' : IDL.Bool,
  'answerText' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionAttempt = IDL.Record({
  'difficulty' : IDL.Float64,
  'chosenAnswerIndex' : IDL.Nat,
  'isCorrect' : IDL.Bool,
  'questionId' : IDL.Text,
  'responseTime' : IDL.Nat,
});
export const IQTestScoreReport = IDL.Record({
  'finalIQScore' : IDL.Nat,
  'attempts' : IDL.Vec(SessionAttempt),
  'normalizedIQScore' : IDL.Float64,
  'correctAnswers' : IDL.Nat,
  'elapsedTime' : IDL.Nat,
  'averageDifficulty' : IDL.Float64,
  'resultSummary' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AnswerDTO = IDL.Record({ 'answerText' : IDL.Text });
export const QuestionDTO = IDL.Record({
  'id' : IDL.Text,
  'answers' : IDL.Vec(AnswerDTO),
  'difficulty' : IDL.Float64,
  'explanation' : IDL.Text,
  'questionText' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Vec(Answer), IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateIQScore' : IDL.Func(
      [IDL.Vec(SessionAttempt), IDL.Nat],
      [IQTestScoreReport],
      [],
    ),
  'deleteQuestion' : IDL.Func([IDL.Text], [], []),
  'getCachedScore' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IQTestScoreReport)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getQuestionsInRange' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(QuestionDTO)],
      ['query'],
    ),
  'getRecommendedQuestions' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Nat],
      [IDL.Vec(QuestionDTO)],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByText' : IDL.Func([IDL.Text], [IDL.Vec(QuestionDTO)], ['query']),
  'submitAnswer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'updateQuestion' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Vec(Answer), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Answer = IDL.Record({
    'isCorrect' : IDL.Bool,
    'answerText' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionAttempt = IDL.Record({
    'difficulty' : IDL.Float64,
    'chosenAnswerIndex' : IDL.Nat,
    'isCorrect' : IDL.Bool,
    'questionId' : IDL.Text,
    'responseTime' : IDL.Nat,
  });
  const IQTestScoreReport = IDL.Record({
    'finalIQScore' : IDL.Nat,
    'attempts' : IDL.Vec(SessionAttempt),
    'normalizedIQScore' : IDL.Float64,
    'correctAnswers' : IDL.Nat,
    'elapsedTime' : IDL.Nat,
    'averageDifficulty' : IDL.Float64,
    'resultSummary' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AnswerDTO = IDL.Record({ 'answerText' : IDL.Text });
  const QuestionDTO = IDL.Record({
    'id' : IDL.Text,
    'answers' : IDL.Vec(AnswerDTO),
    'difficulty' : IDL.Float64,
    'explanation' : IDL.Text,
    'questionText' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Vec(Answer), IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateIQScore' : IDL.Func(
        [IDL.Vec(SessionAttempt), IDL.Nat],
        [IQTestScoreReport],
        [],
      ),
    'deleteQuestion' : IDL.Func([IDL.Text], [], []),
    'getCachedScore' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IQTestScoreReport)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getQuestionsInRange' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(QuestionDTO)],
        ['query'],
      ),
    'getRecommendedQuestions' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Nat],
        [IDL.Vec(QuestionDTO)],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByText' : IDL.Func([IDL.Text], [IDL.Vec(QuestionDTO)], ['query']),
    'submitAnswer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'updateQuestion' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Vec(Answer), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };